server:
  port: 8081
  servlet:
    context-path: /hiep

spring:
  application:
    name: LeaveManagement

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Leave_Management;encrypt=true;trustServerCertificate=true
    username: sa
    password: hiep2004
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create
    show-sql: true